
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER} #e_rental_db_wb9a_user
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Additional configurations for connection pooling (optional)
  datasource.hikari:
    maximum-pool-size: 10
    minimum-idle: 5
    idle-timeout: 30000
    max-lifetime: 1800000
    connection-timeout: 20000


gcp:
  bucket:
    name: ${BUCKET_NAME}

server:
  port: 9090


#    dialect: org.hibernate.dialect.PostgreSQLDialect
#      URL: jdbc:postgresql://dpg-ct5d6dl2ng1s738mtm3g-a.oregon-postgres.render.com:5432/e_rental_db_wb9a

